# For local development 
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: courses-app-mongo
    environment:
      MONGO_INITDB_DATABASE: courses-db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - '27017:27017'
